# Generated by Django 2.1.7 on 2019-03-28 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_recipe_imge'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='imge',
            new_name='image',
        ),
    ]
